version: 2
updates:
  # - package-ecosystem: "maven"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"
  #   labels:
  #     - "dependencies"
  #     - "chore"
  #     - "safe-to-test"

  - package-ecosystem: "docker"
    directory: "/src/container"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "chore"
      - "safe-to-test"
